[servers]
zabbix-server ansible_host=192.168.107.136

[agents]
zabbix-agent ansible_host=192.168.107.135

[all:vars]
ansible_user=administrator
ansible_become=true
ansible_python_interpreter=/usr/bin/python3

timezone=Asia/Tehran
zabbix_server_ip=192.168.107.136
